vim.keymap.set('n', ',gg', '<cmd>G<cr>', { desc = 'git status' })
vim.keymap.set('n', ',gt', '<cmd>G commit<cr>', { desc = 'git commit' })
vim.keymap.set('n', ',gp', '<cmd>G push<cr>', { desc = 'git push' })
vim.keymap.set('n', '<leader>gg', '<cmd>G<cr>', { desc = 'git status' })
vim.keymap.set('n', '<leader>gt', '<cmd>G commit<cr>', { desc = 'git commit' })
vim.keymap.set('n', '<leader>gp', '<cmd>G push<cr>', { desc = 'git push' })
