vim.api.nvim_set_keymap('i', ',,a', 'ä', { noremap = true })
vim.api.nvim_set_keymap('i', ',,o', 'ö', { noremap = true })
vim.api.nvim_set_keymap('i', ',,u', 'ü', { noremap = true })
vim.api.nvim_set_keymap('i', ',,A', 'Ä', { noremap = true })
vim.api.nvim_set_keymap('i', ',,O', 'Ö', { noremap = true })
vim.api.nvim_set_keymap('i', ',,U', 'Ü', { noremap = true })
vim.api.nvim_set_keymap('i', ',,s', 'ß', { noremap = true })
